
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    ports:
      - 3000:3000
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
