import {Harmattan } from "next/font/google";
import "./globals.css";

const harmattan = Harmattan({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={harmattan.className}>{children}</body>
    </html>
  );
}
